export const textes = [
  "Le contenu est roi - Bill Gates",
  "Si votre application est lente, personne ne l'utilisera - Mark Zuckerberg",
  "Le design n'est pas ce à quoi cela ressemble, c'est comment cela fonctionne - Steve Jobs",
  "L'expérience utilisateur est tout - Don Norman",
  "Les frameworks viennent et partent, mais les compétences fondamentales d'un développeur restent - Chris Coyier",
  "Le design est un plan pour arriver à un objectif - Mike Monteiro",
  "Commencez par résoudre le problème, puis écrivez le code - John Johnson",
  "Tout ce qui est conçu pour tout le monde finit par ne satisfaire personne - Paul Rand",
  "Les bonnes pratiques ne sont pas universelles, mais contextuelles - Luke Wroblewski",
  "Les développeurs web sont les artisans du 21ème siècle - Chris Coyier",
  "Le mobile est l'avenir - Eric Schmidt",
  "Le design n'est pas juste une solution, c'est la façon dont vous posez la question - Terry Storch",
  "Le développement est un art autant qu'une science - Dan Brown",
  "Le design est plus que de jolis pixels, c'est la résolution de problèmes - Mike Monteiro",
  "Le mobile est en train de changer le monde - Mary Meeker",
  "L'interface utilisateur est comme une blague. Si vous devez l'expliquer, c'est qu'elle n'est pas bonne - Martin LeBlanc",
  "Un site web devrait être construit pour les utilisateurs, pas pour les concepteurs - Jesse James Garrett",
  "Le développement mobile est le futur de l'informatique - Eric Schmidt",
  "Le design, c'est ce qui relie la fonction à l'apparence - Steve Jobs",
  "Un bon design est évident. Un excellent design est transparent - Joe Sparano",
  "Le développement web est un marathon, pas un sprint - Chris Coyier",
  "Le mobile est l'interface de la nouvelle génération - Paul Saffo",
  "Le design ne doit pas seulement être fonctionnel, il doit aussi être plaisant - Raymond Loewy",
  "Le succès de votre application ne dépend pas seulement de sa qualité, mais aussi de la qualité de son design - Steve Jobs",
  "La qualité de votre code détermine la qualité de votre application - Jason Gorman",
  "Le mobile a dépassé le desktop en tant que moyen le plus utilisé pour accéder à Internet - StatCounter",
  "Le design est là pour simplifier les choses, pas les compliquer - Tim Cook",
  "Les bugs sont des erreurs de design - Tom Cargill",
  "Le développement mobile n'est pas une extension du développement web, c'est un univers différent - Maxime Huran",
  "La simplicité est la sophistication ultime - Leonardo da Vinci",
  "Le développement web est une bataille constante entre les ingénieurs essayant de simplifier les choses et les marketers essayant de les compliquer - Craig Ladwig",
  "Le design est une réponse à une question. L'art est une question à une réponse que personne ne connaît - John Maeda",
  "Le développement web est une course sans fin pour la perfection - Mark Dalgleish",
];
