export const textes = [
  "Le contenu est roi — Bill Gates",
  "Si votre application est lente, personne ne l'utilisera — Mark Zuckerberg",
  "Le design n'est pas ce à quoi cela ressemble, c'est comment cela fonctionne — Steve Jobs",
  "L'expérience utilisateur est tout — Don Norman",
  "Les frameworks viennent et partent, mais les compétences fondamentales restent — Chris Coyier",
  "Le design est un plan pour arriver à un objectif — Mike Monteiro",
  "Commencez par résoudre le problème, puis écrivez le code — John Johnson",
  "Tout ce qui est conçu pour tout le monde finit par ne satisfaire personne — Paul Rand",
  "Les bonnes pratiques ne sont pas universelles, mais contextuelles — Luke Wroblewski",
  "Les développeurs web sont les artisans du 21ème siècle — Chris Coyier",
  "Le mobile est l'avenir — Eric Schmidt",
  "Le développement est un art autant qu'une science — Dan Brown",
  "Le mobile est en train de changer le monde — Mary Meeker",
  "Un site web devrait être construit pour les utilisateurs, pas pour les concepteurs — Jesse James Garrett",
  "Le design, c'est ce qui relie la fonction à l'apparence — Steve Jobs",
  "Un bon design est évident. Un excellent design est transparent — Joe Sparano",
  "Le développement web est un marathon, pas un sprint — Chris Coyier",
  "Le design ne doit pas seulement être fonctionnel, il doit aussi être plaisant — Raymond Loewy",
  "La qualité de votre code détermine la qualité de votre application — Jason Gorman",
  "Le design est là pour simplifier les choses, pas les compliquer — Tim Cook",
  "Les bugs sont des erreurs de design — Tom Cargill",
  "La simplicité est la sophistication ultime — Leonardo da Vinci",
];
